package calcx;

public enum TokenType {
    NUM, INT_VAR, BOOL_KEYWORD, BOOLVAL, BOOL, COLON, SEMICOLON, AND, NOT, OR,EQUALS, PLUS, MINUS, DIVIDE, MULTIPLY, POWER, MODULUS, INT_KEYWORD, END_OF_FILE, NULL_TOKEN 
}
